version: '3.7'
services: 
  gims-timescaledb: 
    image: timescale/timescaledb-ha:pg14-latest
    container_name: gims-timescaledb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ppaallmm
      - POSTGRES_DB=gims
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./gims.bak:/var/gims.bak
  gims-backend:
    container_name: gims-backend
    build: 
      context: ./
      dockerfile: Dockerfile
    image: gims-backend
    depends_on:
      - gims-timescaledb
    env_file:
      - .env
    restart: on-failure
    networks:
      - default
    ports:
    - "8081:8081"
  # dashboard-frontend:
  #   container_name: dashboard-frontend
  #   build: 
  #     context: ./dashboard-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   depends_on: 
  #     - dashboard-backend
  #   volumes:
  #     - ./dashboard-frontend:/opt/dashboard-frontend
  #     - /opt/dashboard-frontend/node_modules
volumes: 
  data: